export enum MaterialProcessingStage {
  UPLOADED = "UPLOADED",
  PROCESSING = "PROCESSING",
  CHUNKING = "CHUNKING",
  EMBEDDING = "EMBEDDING",
  GENERATING = "GENERATING",
  COMPLETED = "COMPLETED",
  FAILED = "FAILED",
}
