export enum NotificationType {
  LESSON_ASSIGNED = "LESSON_ASSIGNED",
  QUIZ_COMPLETED = "QUIZ_COMPLETED",
  MATERIAL_PROCESSED = "MATERIAL_PROCESSED",
  REVISION_REMINDER = "REVISION_REMINDER",
  INVITATION = "INVITATION",
  ACHIEVEMENT_UNLOCKED = "ACHIEVEMENT_UNLOCKED",
  XP_EARNED = "XP_EARNED",
}
